echo "Pulling Rosters"
node roster.js mia
node roster.js no
node roster.js den
node roster.js lac
node roster.js phx
node roster.js dal
node roster.js mil
node roster.js gs
node roster.js bos
node roster.js bkn
node roster.js lal
node roster.js cle
node roster.js cha
node roster.js ind
node roster.js ny
node roster.js orl
node roster.js phi
node roster.js wsh
node roster.js tor
node roster.js chi
node roster.js atl
node roster.js hou
node roster.js okc
node roster.js mem
node roster.js sa
node roster.js min
node roster.js det
node roster.js sac
node roster.js por
node roster.js utah